# Generated by Django 6.0 on 2026-01-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('url', 'URL'), ('text', 'Text')], max_length=20),
        ),
    ]
