# Generated by Django 5.2.10 on 2026-02-10 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0005_analysisbatch_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbatch',
            name='job_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='evaluation_metrics',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='model_agreement',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='retrieved_chunks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddConstraint(
            model_name='analysisbatch',
            constraint=models.UniqueConstraint(fields=('job_id',), name='unique_job_id'),
        ),
    ]
