# Generated by Django 5.2.10 on 2026-03-06 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0007_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbatch',
            name='conversation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='router.conversation'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='query',
            field=models.TextField(default=''),
        ),
    ]
