# Generated by Django 5.2.10 on 2026-03-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0008_analysisbatch_conversation_analysisresult_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='router.document'),
        ),
    ]
