# Generated by Django 5.2.10 on 2026-03-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0009_conversation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvector',
            name='method',
            field=models.CharField(choices=[('dense', 'Dense'), ('sparse', 'Sparse'), ('hybrid', 'Hybrid')], default='dense', max_length=20),
        ),
    ]
