# Generated by Django 5.2.10 on 2026-03-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0010_documentvector_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='model_agreement',
        ),
    ]
