# Generated by Django 5.2.15 on 2026-08-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0012_analysisbatch_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('url', 'URL'), ('text', 'Text'), ('txt', 'TXT'), ('md', 'Markdown'), ('markdown', 'Markdown')], max_length=20),
        ),
    ]
