# Generated by Django 6.1.1 on 2026-09-16 10:43

from django.db import migrations, models


def archive_duplicate_variants(apps, schema_editor):
    Result = apps.get_model('router', 'AnalysisResult')
    records = Result.objects.using(schema_editor.connection.alias)
    duplicates = records.values('batch_id', 'method', 'ai_model').annotate(count=models.Count('id')).filter(count__gt=1)
    for group in duplicates.iterator():
        rows = list(records.filter(**{key: group[key] for key in ('batch_id', 'method', 'ai_model')}).order_by('-created_at', '-id'))
        # Prefer a successful answer, retaining older outcomes in its metrics
        # so installing the uniqueness constraint does not lose their contents.
        keeper = next((row for row in rows if row.answer.strip()), rows[0])
        superseded = [row for row in rows if row.pk != keeper.pk]
        archive = [{
            'id': row.pk, 'query': row.query, 'answer': row.answer,
            'retrieved_chunks': row.retrieved_chunks,
            'evaluation_metrics': row.evaluation_metrics,
            'created_at': row.created_at.isoformat(),
        } for row in superseded]
        metrics = keeper.evaluation_metrics or []
        keeper.evaluation_metrics = ({**metrics, 'superseded_results': archive} if isinstance(metrics, dict)
                                     else [*metrics, {'name': 'superseded_results', 'value': archive}])
        keeper.save(update_fields=['evaluation_metrics'])
        records.filter(pk__in=[row.pk for row in superseded]).delete()
    records.filter(answer='').update(error_message='The saved analysis has no answer. Run Deep Analysis again to retry.', error_code='empty_model_response', retryable=True)


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0013_alter_document_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbatch',
            name='execution_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisbatch',
            name='execution_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(archive_duplicate_variants, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.UniqueConstraint(fields=('batch', 'method', 'ai_model'), name='unique_analysis_variant'),
        ),
    ]
