# Use a specific Node version (e.g., the one from your previous request or latest LTS)
FROM node:22.7-alpine AS base
WORKDIR /app

# Copy package.json and lock file
COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]