# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy requirements first for caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Make port 8000 available
EXPOSE 8000

# Command to run when the container starts.
# This will execute "python manage.py migrate --noinput"
# AND THEN "python manage.py runserver 0.0.0.0:8000"
# The "&&" ensures the second command only runs if the first succeeds.
# This command is executed by /bin/sh -c "..."
CMD python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000