services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ragreader_backend
    ports:
      - "8050:8000"
    depends_on:
      - redis
      - postgres
  
    env_file:
      - .env

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ragreader_worker
    command: celery -A backend worker -l info
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ragreader_frontend
    ports:
      - "5150:5176"
    env_file:
      - ./frontend/.env

  redis:
    image: redis:7-alpine
    container_name: ragreader_redis
    ports:
      - "6350:6379"

  postgres:
    image: postgres:16-alpine
    container_name: ragreader_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./postgres:/var/lib/postgresql/data
